export const getBannerType = 'get/banner'
export const getBannerByIdType = 'getById/banner'
export const postBannerType = 'post/banner'
export const putBannerType = 'put/banner'
export const deleteBannerType = 'delete/banner'
