export const getProductType = 'get/product'
export const getProductByIdType = 'getById/product'
export const postProductType = 'post/product'
export const putProductType = 'put/product'
export const deleteProductType = 'delete/product'
